Task 1 — Data Cleaning & Preprocessing

In [1]:
import pandas as pd

df = pd.read_csv("Dataset.csv")

df

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"
...,...,...,...,...,...,...,...,...,...,...
8785,s8797,TV Show,Yunus Emre,Not Given,Turkey,1/17/2017,2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas"
8786,s8798,TV Show,Zak Storm,Not Given,United States,9/13/2018,2016,TV-Y7,3 Seasons,Kids' TV
8787,s8801,TV Show,Zindagi Gulzar Hai,Not Given,Pakistan,12/15/2016,2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ..."
8788,s8784,TV Show,Yoko,Not Given,Pakistan,6/23/2018,2016,TV-Y,1 Season,Kids' TV
8789,s8786,TV Show,YOM,Not Given,Pakistan,6/7/2018,2016,TV-Y7,1 Season,Kids' TV

In [2]:
df.head()

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"

In [3]:
df.shape

(8790, 10)

In [4]:
print(df.dtypes)

show_id           str
type              str
title             str
director          str
country           str
date_added        str
release_year    int64
rating            str
duration          str
listed_in         str
dtype: object

Step 2 — Identify Missing & Duplicate Records

In [5]:
missing = df.isnull().sum()
print(missing)

show_id         0
type            0
title           0
director        0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
dtype: int64

In [6]:
print(df.duplicated().sum())

0

Step 3 — Handle Null Values & Inconsistent Formats

In [7]:
print(df["type"].unique())

<ArrowStringArray>
['Movie', 'TV Show']
Length: 2, dtype: str

In [8]:
print(df["rating"].unique())

<ArrowStringArray>
[   'PG-13',    'TV-MA',    'TV-PG',    'TV-14',    'TV-Y7',     'TV-Y',
       'PG',     'TV-G',        'R',        'G',    'NC-17',       'NR',
 'TV-Y7-FV',       'UR']
Length: 14, dtype: str

In [9]:
print(df["country"].unique())

<ArrowStringArray>
[       'United States',               'France',               'Brazil',
       'United Kingdom',                'India',              'Germany',
             'Pakistan',            'Not Given',                'China',
         'South Africa',                'Japan',              'Nigeria',
                'Spain',          'Philippines',            'Australia',
            'Argentina',               'Canada',            'Hong Kong',
                'Italy',          'New Zealand',                'Egypt',
             'Colombia',               'Mexico',              'Belgium',
          'Switzerland',               'Taiwan',             'Bulgaria',
               'Poland',          'South Korea',         'Saudi Arabia',
             'Thailand',            'Indonesia',               'Kuwait',
             'Malaysia',              'Vietnam',              'Lebanon',
              'Romania',                'Syria', 'United Arab Emirates',
               'Sweden',            'Mauritius',              'Austria',
               'Turkey',       'Czech Republic',             'Cameroon',
          'Netherlands',              'Ireland',               'Russia',
                'Kenya',                'Chile',              'Uruguay',
           'Bangladesh',             'Portugal',              'Hungary',
               'Norway',            'Singapore',              'Iceland',
               'Serbia',              'Namibia',                 'Peru',
           'Mozambique',                'Ghana',             'Zimbabwe',
               'Israel',              'Finland',              'Denmark',
             'Paraguay',             'Cambodia',              'Georgia',
         'Soviet Union',               'Greece',         'West Germany',
                 'Iran',            'Venezuela',             'Slovenia',
            'Guatemala',              'Jamaica',              'Somalia',
              'Croatia',               'Jordan',           'Luxembourg',
              'Senegal',              'Belarus',          'Puerto Rico',
               'Cyprus',              'Ukraine']
Length: 86, dtype: str

In [10]:
print(df["duration"].unique())

<ArrowStringArray>
[    '90 min',   '1 Season',     '91 min',    '125 min',  '9 Seasons',
    '104 min',     '87 min',    '127 min',     '76 min',     '71 min',
 ...
    '205 min',    '201 min',    '191 min', '10 Seasons', '17 Seasons',
 '13 Seasons',     '10 min',    '312 min', '12 Seasons', '11 Seasons']
Length: 220, dtype: str

In [11]:
print(df["duration"].unique())

<ArrowStringArray>
[    '90 min',   '1 Season',     '91 min',    '125 min',  '9 Seasons',
    '104 min',     '87 min',    '127 min',     '76 min',     '71 min',
 ...
    '205 min',    '201 min',    '191 min', '10 Seasons', '17 Seasons',
 '13 Seasons',     '10 min',    '312 min', '12 Seasons', '11 Seasons']
Length: 220, dtype: str

Step 4 — Transform Categorical & Date Columns

In [12]:
df["type"] = df["type"].astype("category")

In [13]:
print(df["type"].dtype)

category

In [14]:
df["rating"] = df["rating"].astype("category")

In [15]:
print(df["rating"].dtype)

category

In [16]:
df["country"] = df["country"].astype("category")

In [17]:
print(df["country"].dtype)

category

In [18]:
df["date_added"] = pd.to_datetime(
    df["date_added"],
    errors="coerce"
)

In [19]:
print(df["date_added"].dtype)

datetime64[us]

In [20]:
print(df["date_added"].isnull().sum())

0

Step 5 — Create a Clean Dataset for Further Analysis

In [21]:
print(df.shape)

(8790, 10)

In [22]:
print(df.isnull().sum())

show_id         0
type            0
title           0
director        0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
dtype: int64

In [23]:
print(df.duplicated().sum())

0

In [24]:
print(df.dtypes)

show_id                    str
type                  category
title                      str
director                   str
country               category
date_added      datetime64[us]
release_year             int64
rating                category
duration                   str
listed_in                  str
dtype: object

In [25]:
df.to_csv("clean_netflix.csv", index=False)